// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/home";
  };
  "pages/root/index.tsx": {
    id: "pages/root/index";
    page: "/";
  };
  "pages/auth/index.tsx": {
    id: "pages/auth/index";
    page: "/auth";
  };
  "pages/home/index.tsx": {
    id: "pages/home/index";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "pages/root/index": typeof import("./src/pages/root/index.tsx");
  "pages/auth/index": typeof import("./src/pages/auth/index.tsx");
  "pages/home/index": typeof import("./src/pages/home/index.tsx");
};